apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    application: hello-chris
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/sync-options: "SkipDryRunOnMissingResource=true"
    env: development
  name: hello-chris
  namespace: hello-chris
