apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: small-quota
  annotations:
    policies.kyverno.io/title: Add Quota
    policies.kyverno.io/category: Multi-Tenancy, EKS Best Practices
    policies.kyverno.io/subject: ResourceQuota, LimitRange
    policies.kyverno.io/minversion: 1.6.0
    policies.kyverno.io/description: >-
      To better control the number of resources that can be created in a given
      Namespace and provide default resource consumption limits for Pods,
      ResourceQuota and LimitRange resources are recommended.
      This policy will generate ResourceQuota and LimitRange resources when
      a new Namespace is created.      
spec:
  validationFailureAction: enforce
  rules:
  - name: small-quota
    match:
      resources: 
        kinds:
        - Namespace
        selector:
          matchLabels:
            size: "small"
    generate:
      apiVersion: v1
      kind: ResourceQuota
      name: small-resourcequota
      synchronize: true
      namespace: "{{request.object.metadata.name}}"
      data:
        spec:
          hard:
            requests.cpu: '4'
            requests.memory: '8Gi'
            limits.cpu: '4'
            limits.memory: '8Gi'
  - name: generate-limitrange
    match:
      any:
      - resources:
          kinds:
          - Namespace
    generate:
      apiVersion: v1
      kind: LimitRange
      name: small-limitrange
      synchronize: true
      namespace: "{{request.object.metadata.name}}"
      data:
        spec:
          limits:
          - default:
              cpu: 250m
              memory: 1Gi
            defaultRequest:
              cpu: 100m
              memory: 256Mi
            type: Container
          apiGroup: rbac.authorization.k8s.io

---
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: large-quota
  annotations:
    policies.kyverno.io/title: Add Quota
    policies.kyverno.io/category: Multi-Tenancy, EKS Best Practices
    policies.kyverno.io/subject: ResourceQuota, LimitRange
    policies.kyverno.io/minversion: 1.6.0
    policies.kyverno.io/description: >-
      To better control the number of resources that can be created in a given
      Namespace and provide default resource consumption limits for Pods,
      ResourceQuota and LimitRange resources are recommended.
      This policy will generate ResourceQuota and LimitRange resources when
      a new Namespace is created.      
spec:
  validationFailureAction: enforce
  rules:
  - name: large-quota
    match:
      resources: 
        kinds:
        - Namespace
        selector:
          matchLabels:
            size: "large"
    generate:
      apiVersion: v1
      kind: ResourceQuota
      name: large-resourcequota
      synchronize: true
      namespace: "{{request.object.metadata.name}}"
      data:
        spec:
          hard:
            requests.cpu: '8'
            requests.memory: '16Gi'
            limits.cpu: '8'
            limits.memory: '16Gi'
  - name: generate-limitrange
    match:
      any:
      - resources:
          kinds:
          - Namespace
    generate:
      apiVersion: v1
      kind: LimitRange
      name: large-limitrange
      synchronize: true
      namespace: "{{request.object.metadata.name}}"
      data:
        spec:
          limits:
          - default:
              cpu: 500m
              memory: 1Gi
            defaultRequest:
              cpu: 200m
              memory: 500Mi
            type: Container