---
apiVersion: v1
kind: Namespace
metadata:
  name: hello-chris
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    argocd.argoproj.io/managed-by: openshift-gitops
    secrets: hello-world
    admin: admin
    viewer: test
    enforced: "true"
    size: large
spec: