apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: viewer-rolebinding
spec: 
  validationFailureAction: enforce
  rules:
  - name: viewer-rolebinding
    match:
      resources:
        kinds:
        - Namespace
        selector:
          matchLabels:
            enforced: "true"
    generate:
      kind: RoleBinding
      apiVersion: rbac.authorization.k8s.io/v1
      name: viewer-rolebinding
      namespace: "{{request.object.metadata.name}}"
      data:  
        subjects:
        - kind: Group
          name: "{{request.object.metadata.labels.viewer}}"
          apiGroup: rbac.authorization.k8s.io
        roleRef:
          kind: ClusterRole
          name: view
          apiGroup: rbac.authorization.k8s.io