apiVersion: v1
kind: Service
metadata:
  labels:
    app: hello-chris
    app.kubernetes.io/component: hello-chris
    app.kubernetes.io/instance: hello-chris
  annotations:
    argocd.argoproj.io/sync-wave: "4"
    argocd.argoproj.io/sync-options: "SkipDryRunOnMissingResource=true"
  name: hello-chris
  namespace: hello-chris
spec:
  ports:
  - name: 8080-tcp
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    deployment: hello-chris
status:
  loadBalancer: {}
